global:
  scrape_interval: 180s
  evaluation_interval: 30s
  scrape_timeout: 60s
alerting:
  alertmanagers:
  - static_configs:
    - targets:
       - 192.168.10.241:9093
rule_files:
  - all.rules
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
        labels:
          alias: prometheus
  - job_name: 'presmtrp01'
    static_configs:
      - targets: ['192.168.10.241:9100']
        labels:
          alias: presmtrp01
  - job_name: 'presmtelk01'
    static_configs:
      - targets: ['192.168.10.81:9100']
        labels:
          alias: presmtelk01
